image: docker:latest

services:
  - docker:dind
  - mysql:latest

variables:
  MYSQL_DATABASE: weeby
  MYSQL_ROOT_PASSWORD: weeby2019

stages:
  - build-server
  - build-docker

maven-build:
  image: maven:3-jdk-8
  stage: build-server
  script:
    - mvn clean package -B -DskipTests
  artifacts:
    paths:
      - weeby.war

build docker:
  image: docker:dind
  stage: build-docker
  script: docker build weeby.war .

