image: docker:latest

services:
  - docker:dind

stages:
  - build-server
  - build-docker

maven-build:
  image: maven:3-jdk-8
  stage: build-server
  script:
    - cd weeby-server
    - mvn clean package -B -DskipTests
  artifacts:
    paths:
      - /builds/Frehon/Weeby/weeby-server/target/weeby.war
      
build docker:
  stage: build-docker
  script:
    - cp target/* weeby-server
    - docker login -u tomaszgogolewski -p TIxao16janakonda666 docker.io
    - docker build -t tomaszgogolewski/weeby-server .
    - docker push index.docker.io/tomaszgogolewski/weeby-server:latest


